package br.com.agr.model.entities;
// Generated 18/05/2015 08:05:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Atendimento generated by hbm2java
 */
@Entity
@Table(name="atendimento"
    ,schema="public"
)
public class Atendimento  implements java.io.Serializable {


     private int atendimentoId;
     private Integer atendimentoCodigoPaciente;
     private Integer atendimentoCodigoExame;
     private Integer atendimentoCodigoMedico;
     private Integer atendimentoCodigoPlano;
     private Integer atendimentoResponsavelLaudo;
     private Boolean atendimentoRealizado;
     private Boolean atendimentoLaudo;
     private Boolean atendimentoEntregue;

    public Atendimento() {
    }

	
    public Atendimento(int atendimentoId) {
        this.atendimentoId = atendimentoId;
    }
    public Atendimento(int atendimentoId, Integer atendimentoCodigoPaciente, Integer atendimentoCodigoExame, Integer atendimentoCodigoMedico, Integer atendimentoCodigoPlano, Integer atendimentoResponsavelLaudo, Boolean atendimentoRealizado, Boolean atendimentoLaudo, Boolean atendimentoEntregue) {
       this.atendimentoId = atendimentoId;
       this.atendimentoCodigoPaciente = atendimentoCodigoPaciente;
       this.atendimentoCodigoExame = atendimentoCodigoExame;
       this.atendimentoCodigoMedico = atendimentoCodigoMedico;
       this.atendimentoCodigoPlano = atendimentoCodigoPlano;
       this.atendimentoResponsavelLaudo = atendimentoResponsavelLaudo;
       this.atendimentoRealizado = atendimentoRealizado;
       this.atendimentoLaudo = atendimentoLaudo;
       this.atendimentoEntregue = atendimentoEntregue;
    }
   
     @Id 

    
    @Column(name="atendimento_id", unique=true, nullable=false)
    public int getAtendimentoId() {
        return this.atendimentoId;
    }
    
    public void setAtendimentoId(int atendimentoId) {
        this.atendimentoId = atendimentoId;
    }

    
    @Column(name="atendimento_codigo_paciente")
    public Integer getAtendimentoCodigoPaciente() {
        return this.atendimentoCodigoPaciente;
    }
    
    public void setAtendimentoCodigoPaciente(Integer atendimentoCodigoPaciente) {
        this.atendimentoCodigoPaciente = atendimentoCodigoPaciente;
    }

    
    @Column(name="atendimento_codigo_exame")
    public Integer getAtendimentoCodigoExame() {
        return this.atendimentoCodigoExame;
    }
    
    public void setAtendimentoCodigoExame(Integer atendimentoCodigoExame) {
        this.atendimentoCodigoExame = atendimentoCodigoExame;
    }

    
    @Column(name="atendimento_codigo_medico")
    public Integer getAtendimentoCodigoMedico() {
        return this.atendimentoCodigoMedico;
    }
    
    public void setAtendimentoCodigoMedico(Integer atendimentoCodigoMedico) {
        this.atendimentoCodigoMedico = atendimentoCodigoMedico;
    }

    
    @Column(name="atendimento_codigo_plano")
    public Integer getAtendimentoCodigoPlano() {
        return this.atendimentoCodigoPlano;
    }
    
    public void setAtendimentoCodigoPlano(Integer atendimentoCodigoPlano) {
        this.atendimentoCodigoPlano = atendimentoCodigoPlano;
    }

    
    @Column(name="atendimento_responsavel_laudo")
    public Integer getAtendimentoResponsavelLaudo() {
        return this.atendimentoResponsavelLaudo;
    }
    
    public void setAtendimentoResponsavelLaudo(Integer atendimentoResponsavelLaudo) {
        this.atendimentoResponsavelLaudo = atendimentoResponsavelLaudo;
    }

    
    @Column(name="atendimento_realizado")
    public Boolean getAtendimentoRealizado() {
        return this.atendimentoRealizado;
    }
    
    public void setAtendimentoRealizado(Boolean atendimentoRealizado) {
        this.atendimentoRealizado = atendimentoRealizado;
    }

    
    @Column(name="atendimento_laudo")
    public Boolean getAtendimentoLaudo() {
        return this.atendimentoLaudo;
    }
    
    public void setAtendimentoLaudo(Boolean atendimentoLaudo) {
        this.atendimentoLaudo = atendimentoLaudo;
    }

    
    @Column(name="atendimento_entregue")
    public Boolean getAtendimentoEntregue() {
        return this.atendimentoEntregue;
    }
    
    public void setAtendimentoEntregue(Boolean atendimentoEntregue) {
        this.atendimentoEntregue = atendimentoEntregue;
    }




}


