package br.com.agr.model.entities;
// Generated 18/05/2015 08:05:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="empresa"
    ,schema="public"
)
public class Empresa  implements java.io.Serializable {


     private int empresaId;
     private String empresaNome;
     private String empresaRazao;
     private String empresaLogradoro;
     private String empresaNumero;
     private String empresaComplemento;
     private String empresaBairro;
     private String empresaCidade;
     private String empresaUf;
     private String empresaTelefone;
     private String empresaFax;
     private String empresaCelular;
     private String empresaMail;
     private String empresaSite;
     private String empresaCnpj;

    public Empresa() {
    }

	
    public Empresa(int empresaId) {
        this.empresaId = empresaId;
    }
    public Empresa(int empresaId, String empresaNome, String empresaRazao, String empresaLogradoro, String empresaNumero, String empresaComplemento, String empresaBairro, String empresaCidade, String empresaUf, String empresaTelefone, String empresaFax, String empresaCelular, String empresaMail, String empresaSite, String empresaCnpj) {
       this.empresaId = empresaId;
       this.empresaNome = empresaNome;
       this.empresaRazao = empresaRazao;
       this.empresaLogradoro = empresaLogradoro;
       this.empresaNumero = empresaNumero;
       this.empresaComplemento = empresaComplemento;
       this.empresaBairro = empresaBairro;
       this.empresaCidade = empresaCidade;
       this.empresaUf = empresaUf;
       this.empresaTelefone = empresaTelefone;
       this.empresaFax = empresaFax;
       this.empresaCelular = empresaCelular;
       this.empresaMail = empresaMail;
       this.empresaSite = empresaSite;
       this.empresaCnpj = empresaCnpj;
    }
   
     @Id 

    
    @Column(name="empresa_id", unique=true, nullable=false)
    public int getEmpresaId() {
        return this.empresaId;
    }
    
    public void setEmpresaId(int empresaId) {
        this.empresaId = empresaId;
    }

    
    @Column(name="empresa_nome", length=50)
    public String getEmpresaNome() {
        return this.empresaNome;
    }
    
    public void setEmpresaNome(String empresaNome) {
        this.empresaNome = empresaNome;
    }

    
    @Column(name="empresa_razao", length=50)
    public String getEmpresaRazao() {
        return this.empresaRazao;
    }
    
    public void setEmpresaRazao(String empresaRazao) {
        this.empresaRazao = empresaRazao;
    }

    
    @Column(name="empresa_logradoro", length=50)
    public String getEmpresaLogradoro() {
        return this.empresaLogradoro;
    }
    
    public void setEmpresaLogradoro(String empresaLogradoro) {
        this.empresaLogradoro = empresaLogradoro;
    }

    
    @Column(name="empresa_numero", length=20)
    public String getEmpresaNumero() {
        return this.empresaNumero;
    }
    
    public void setEmpresaNumero(String empresaNumero) {
        this.empresaNumero = empresaNumero;
    }

    
    @Column(name="empresa_complemento", length=40)
    public String getEmpresaComplemento() {
        return this.empresaComplemento;
    }
    
    public void setEmpresaComplemento(String empresaComplemento) {
        this.empresaComplemento = empresaComplemento;
    }

    
    @Column(name="empresa_bairro", length=40)
    public String getEmpresaBairro() {
        return this.empresaBairro;
    }
    
    public void setEmpresaBairro(String empresaBairro) {
        this.empresaBairro = empresaBairro;
    }

    
    @Column(name="empresa_cidade", length=40)
    public String getEmpresaCidade() {
        return this.empresaCidade;
    }
    
    public void setEmpresaCidade(String empresaCidade) {
        this.empresaCidade = empresaCidade;
    }

    
    @Column(name="empresa_uf", length=2)
    public String getEmpresaUf() {
        return this.empresaUf;
    }
    
    public void setEmpresaUf(String empresaUf) {
        this.empresaUf = empresaUf;
    }

    
    @Column(name="empresa_telefone", length=15)
    public String getEmpresaTelefone() {
        return this.empresaTelefone;
    }
    
    public void setEmpresaTelefone(String empresaTelefone) {
        this.empresaTelefone = empresaTelefone;
    }

    
    @Column(name="empresa_fax", length=15)
    public String getEmpresaFax() {
        return this.empresaFax;
    }
    
    public void setEmpresaFax(String empresaFax) {
        this.empresaFax = empresaFax;
    }

    
    @Column(name="empresa_celular", length=15)
    public String getEmpresaCelular() {
        return this.empresaCelular;
    }
    
    public void setEmpresaCelular(String empresaCelular) {
        this.empresaCelular = empresaCelular;
    }

    
    @Column(name="empresa_mail", length=80)
    public String getEmpresaMail() {
        return this.empresaMail;
    }
    
    public void setEmpresaMail(String empresaMail) {
        this.empresaMail = empresaMail;
    }

    
    @Column(name="empresa_site", length=40)
    public String getEmpresaSite() {
        return this.empresaSite;
    }
    
    public void setEmpresaSite(String empresaSite) {
        this.empresaSite = empresaSite;
    }

    
    @Column(name="empresa_cnpj", length=30)
    public String getEmpresaCnpj() {
        return this.empresaCnpj;
    }
    
    public void setEmpresaCnpj(String empresaCnpj) {
        this.empresaCnpj = empresaCnpj;
    }




}


