package br.com.agr.model.entities;
// Generated 18/05/2015 08:05:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Exame generated by hbm2java
 */
@Entity
@Table(name="exame"
    ,schema="public"
)
public class Exame  implements java.io.Serializable {


     private int exameId;
     private String exameNome;
     private String exameDesc;

    public Exame() {
    }

	
    public Exame(int exameId) {
        this.exameId = exameId;
    }
    public Exame(int exameId, String exameNome, String exameDesc) {
       this.exameId = exameId;
       this.exameNome = exameNome;
       this.exameDesc = exameDesc;
    }
   
     @Id 

    
    @Column(name="exame_id", unique=true, nullable=false)
    public int getExameId() {
        return this.exameId;
    }
    
    public void setExameId(int exameId) {
        this.exameId = exameId;
    }

    
    @Column(name="exame_nome", length=80)
    public String getExameNome() {
        return this.exameNome;
    }
    
    public void setExameNome(String exameNome) {
        this.exameNome = exameNome;
    }

    
    @Column(name="exame_desc", length=500)
    public String getExameDesc() {
        return this.exameDesc;
    }
    
    public void setExameDesc(String exameDesc) {
        this.exameDesc = exameDesc;
    }




}


