package br.com.agr.model.entities;
// Generated 18/05/2015 08:05:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Laudo generated by hbm2java
 */
@Entity
@Table(name="laudo"
    ,schema="public"
)
public class Laudo  implements java.io.Serializable {


     private int laudoId;
     private String laudoNome;
     private String laudoCrm;
     private String laudoLogradoro;
     private String laudoNumero;
     private String laudoComplemento;
     private String laudoBairro;
     private String laudoCidade;
     private String laudoMg;
     private String laudoCep;
     private String laudoTelefone;
     private String laudoCelular;
     private String laudoMail;

    public Laudo() {
    }

	
    public Laudo(int laudoId) {
        this.laudoId = laudoId;
    }
    public Laudo(int laudoId, String laudoNome, String laudoCrm, String laudoLogradoro, String laudoNumero, String laudoComplemento, String laudoBairro, String laudoCidade, String laudoMg, String laudoCep, String laudoTelefone, String laudoCelular, String laudoMail) {
       this.laudoId = laudoId;
       this.laudoNome = laudoNome;
       this.laudoCrm = laudoCrm;
       this.laudoLogradoro = laudoLogradoro;
       this.laudoNumero = laudoNumero;
       this.laudoComplemento = laudoComplemento;
       this.laudoBairro = laudoBairro;
       this.laudoCidade = laudoCidade;
       this.laudoMg = laudoMg;
       this.laudoCep = laudoCep;
       this.laudoTelefone = laudoTelefone;
       this.laudoCelular = laudoCelular;
       this.laudoMail = laudoMail;
    }
   
     @Id 

    
    @Column(name="laudo_id", unique=true, nullable=false)
    public int getLaudoId() {
        return this.laudoId;
    }
    
    public void setLaudoId(int laudoId) {
        this.laudoId = laudoId;
    }

    
    @Column(name="laudo_nome", length=50)
    public String getLaudoNome() {
        return this.laudoNome;
    }
    
    public void setLaudoNome(String laudoNome) {
        this.laudoNome = laudoNome;
    }

    
    @Column(name="laudo_crm", length=20)
    public String getLaudoCrm() {
        return this.laudoCrm;
    }
    
    public void setLaudoCrm(String laudoCrm) {
        this.laudoCrm = laudoCrm;
    }

    
    @Column(name="laudo_logradoro", length=80)
    public String getLaudoLogradoro() {
        return this.laudoLogradoro;
    }
    
    public void setLaudoLogradoro(String laudoLogradoro) {
        this.laudoLogradoro = laudoLogradoro;
    }

    
    @Column(name="laudo_numero", length=20)
    public String getLaudoNumero() {
        return this.laudoNumero;
    }
    
    public void setLaudoNumero(String laudoNumero) {
        this.laudoNumero = laudoNumero;
    }

    
    @Column(name="laudo_complemento", length=30)
    public String getLaudoComplemento() {
        return this.laudoComplemento;
    }
    
    public void setLaudoComplemento(String laudoComplemento) {
        this.laudoComplemento = laudoComplemento;
    }

    
    @Column(name="laudo_bairro", length=50)
    public String getLaudoBairro() {
        return this.laudoBairro;
    }
    
    public void setLaudoBairro(String laudoBairro) {
        this.laudoBairro = laudoBairro;
    }

    
    @Column(name="laudo_cidade", length=50)
    public String getLaudoCidade() {
        return this.laudoCidade;
    }
    
    public void setLaudoCidade(String laudoCidade) {
        this.laudoCidade = laudoCidade;
    }

    
    @Column(name="laudo_mg", length=2)
    public String getLaudoMg() {
        return this.laudoMg;
    }
    
    public void setLaudoMg(String laudoMg) {
        this.laudoMg = laudoMg;
    }

    
    @Column(name="laudo_cep", length=20)
    public String getLaudoCep() {
        return this.laudoCep;
    }
    
    public void setLaudoCep(String laudoCep) {
        this.laudoCep = laudoCep;
    }

    
    @Column(name="laudo_telefone", length=20)
    public String getLaudoTelefone() {
        return this.laudoTelefone;
    }
    
    public void setLaudoTelefone(String laudoTelefone) {
        this.laudoTelefone = laudoTelefone;
    }

    
    @Column(name="laudo_celular", length=20)
    public String getLaudoCelular() {
        return this.laudoCelular;
    }
    
    public void setLaudoCelular(String laudoCelular) {
        this.laudoCelular = laudoCelular;
    }

    
    @Column(name="laudo_mail", length=80)
    public String getLaudoMail() {
        return this.laudoMail;
    }
    
    public void setLaudoMail(String laudoMail) {
        this.laudoMail = laudoMail;
    }




}


