package br.com.agr.model.entities;
// Generated 18/05/2015 08:05:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Medico generated by hbm2java
 */
@Entity
@Table(name="medico"
    ,schema="public"
)
public class Medico  implements java.io.Serializable {


     private int medicoId;
     private String medicoNome;
     private String medicoDesc;

    public Medico() {
    }

	
    public Medico(int medicoId) {
        this.medicoId = medicoId;
    }
    public Medico(int medicoId, String medicoNome, String medicoDesc) {
       this.medicoId = medicoId;
       this.medicoNome = medicoNome;
       this.medicoDesc = medicoDesc;
    }
   
     @Id 

    
    @Column(name="medico_id", unique=true, nullable=false)
    public int getMedicoId() {
        return this.medicoId;
    }
    
    public void setMedicoId(int medicoId) {
        this.medicoId = medicoId;
    }

    
    @Column(name="medico_nome", length=80)
    public String getMedicoNome() {
        return this.medicoNome;
    }
    
    public void setMedicoNome(String medicoNome) {
        this.medicoNome = medicoNome;
    }

    
    @Column(name="medico_desc", length=500)
    public String getMedicoDesc() {
        return this.medicoDesc;
    }
    
    public void setMedicoDesc(String medicoDesc) {
        this.medicoDesc = medicoDesc;
    }




}


