package br.com.agr.model.entities;
// Generated 18/05/2015 08:05:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name="paciente"
    ,schema="public"
)
public class Paciente  implements java.io.Serializable {


     private int pacienteId;
     private String pacienteNome;
     private String pacienteCpf;
     private String pacienteRg;
     private String pacienteLogradoro;
     private String pacienteNumero;
     private String pacienteComplemento;
     private String pacienteBairro;
     private String pacienteCidade;
     private String pacienteMg;
     private String pacienteCep;
     private String pacienteTelefone;
     private String pacienteCelular;
     private String pacienteMail;
     private String pacientePai;
     private String pacienteMae;

    public Paciente() {
    }

	
    public Paciente(int pacienteId) {
        this.pacienteId = pacienteId;
    }
    public Paciente(int pacienteId, String pacienteNome, String pacienteCpf, String pacienteRg, String pacienteLogradoro, String pacienteNumero, String pacienteComplemento, String pacienteBairro, String pacienteCidade, String pacienteMg, String pacienteCep, String pacienteTelefone, String pacienteCelular, String pacienteMail, String pacientePai, String pacienteMae) {
       this.pacienteId = pacienteId;
       this.pacienteNome = pacienteNome;
       this.pacienteCpf = pacienteCpf;
       this.pacienteRg = pacienteRg;
       this.pacienteLogradoro = pacienteLogradoro;
       this.pacienteNumero = pacienteNumero;
       this.pacienteComplemento = pacienteComplemento;
       this.pacienteBairro = pacienteBairro;
       this.pacienteCidade = pacienteCidade;
       this.pacienteMg = pacienteMg;
       this.pacienteCep = pacienteCep;
       this.pacienteTelefone = pacienteTelefone;
       this.pacienteCelular = pacienteCelular;
       this.pacienteMail = pacienteMail;
       this.pacientePai = pacientePai;
       this.pacienteMae = pacienteMae;
    }
   
     @Id 

    
    @Column(name="paciente_id", unique=true, nullable=false)
    public int getPacienteId() {
        return this.pacienteId;
    }
    
    public void setPacienteId(int pacienteId) {
        this.pacienteId = pacienteId;
    }

    
    @Column(name="paciente_nome", length=50)
    public String getPacienteNome() {
        return this.pacienteNome;
    }
    
    public void setPacienteNome(String pacienteNome) {
        this.pacienteNome = pacienteNome;
    }

    
    @Column(name="paciente_cpf", length=20)
    public String getPacienteCpf() {
        return this.pacienteCpf;
    }
    
    public void setPacienteCpf(String pacienteCpf) {
        this.pacienteCpf = pacienteCpf;
    }

    
    @Column(name="paciente_rg", length=50)
    public String getPacienteRg() {
        return this.pacienteRg;
    }
    
    public void setPacienteRg(String pacienteRg) {
        this.pacienteRg = pacienteRg;
    }

    
    @Column(name="paciente_logradoro", length=80)
    public String getPacienteLogradoro() {
        return this.pacienteLogradoro;
    }
    
    public void setPacienteLogradoro(String pacienteLogradoro) {
        this.pacienteLogradoro = pacienteLogradoro;
    }

    
    @Column(name="paciente_numero", length=20)
    public String getPacienteNumero() {
        return this.pacienteNumero;
    }
    
    public void setPacienteNumero(String pacienteNumero) {
        this.pacienteNumero = pacienteNumero;
    }

    
    @Column(name="paciente_complemento", length=30)
    public String getPacienteComplemento() {
        return this.pacienteComplemento;
    }
    
    public void setPacienteComplemento(String pacienteComplemento) {
        this.pacienteComplemento = pacienteComplemento;
    }

    
    @Column(name="paciente_bairro", length=50)
    public String getPacienteBairro() {
        return this.pacienteBairro;
    }
    
    public void setPacienteBairro(String pacienteBairro) {
        this.pacienteBairro = pacienteBairro;
    }

    
    @Column(name="paciente_cidade", length=50)
    public String getPacienteCidade() {
        return this.pacienteCidade;
    }
    
    public void setPacienteCidade(String pacienteCidade) {
        this.pacienteCidade = pacienteCidade;
    }

    
    @Column(name="paciente_mg", length=2)
    public String getPacienteMg() {
        return this.pacienteMg;
    }
    
    public void setPacienteMg(String pacienteMg) {
        this.pacienteMg = pacienteMg;
    }

    
    @Column(name="paciente_cep", length=20)
    public String getPacienteCep() {
        return this.pacienteCep;
    }
    
    public void setPacienteCep(String pacienteCep) {
        this.pacienteCep = pacienteCep;
    }

    
    @Column(name="paciente_telefone", length=20)
    public String getPacienteTelefone() {
        return this.pacienteTelefone;
    }
    
    public void setPacienteTelefone(String pacienteTelefone) {
        this.pacienteTelefone = pacienteTelefone;
    }

    
    @Column(name="paciente_celular", length=20)
    public String getPacienteCelular() {
        return this.pacienteCelular;
    }
    
    public void setPacienteCelular(String pacienteCelular) {
        this.pacienteCelular = pacienteCelular;
    }

    
    @Column(name="paciente_mail", length=80)
    public String getPacienteMail() {
        return this.pacienteMail;
    }
    
    public void setPacienteMail(String pacienteMail) {
        this.pacienteMail = pacienteMail;
    }

    
    @Column(name="paciente_pai", length=50)
    public String getPacientePai() {
        return this.pacientePai;
    }
    
    public void setPacientePai(String pacientePai) {
        this.pacientePai = pacientePai;
    }

    
    @Column(name="paciente_mae", length=50)
    public String getPacienteMae() {
        return this.pacienteMae;
    }
    
    public void setPacienteMae(String pacienteMae) {
        this.pacienteMae = pacienteMae;
    }




}


