package br.com.agr.model.entities;
// Generated 18/05/2015 08:05:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Planosaude generated by hbm2java
 */
@Entity
@Table(name="planosaude"
    ,schema="public"
)
public class Planosaude  implements java.io.Serializable {


     private int planoSaudeId;
     private String planoSaudeNome;
     private String planoSaudeDesc;

    public Planosaude() {
    }

	
    public Planosaude(int planoSaudeId) {
        this.planoSaudeId = planoSaudeId;
    }
    public Planosaude(int planoSaudeId, String planoSaudeNome, String planoSaudeDesc) {
       this.planoSaudeId = planoSaudeId;
       this.planoSaudeNome = planoSaudeNome;
       this.planoSaudeDesc = planoSaudeDesc;
    }
   
     @Id 

    
    @Column(name="plano_saude_id", unique=true, nullable=false)
    public int getPlanoSaudeId() {
        return this.planoSaudeId;
    }
    
    public void setPlanoSaudeId(int planoSaudeId) {
        this.planoSaudeId = planoSaudeId;
    }

    
    @Column(name="plano_saude_nome", length=80)
    public String getPlanoSaudeNome() {
        return this.planoSaudeNome;
    }
    
    public void setPlanoSaudeNome(String planoSaudeNome) {
        this.planoSaudeNome = planoSaudeNome;
    }

    
    @Column(name="plano_saude_desc", length=500)
    public String getPlanoSaudeDesc() {
        return this.planoSaudeDesc;
    }
    
    public void setPlanoSaudeDesc(String planoSaudeDesc) {
        this.planoSaudeDesc = planoSaudeDesc;
    }




}


