package br.com.agr.model.entities;
// Generated 18/05/2015 08:05:26 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name="usuario"
    ,schema="public"
)
public class Usuario  implements java.io.Serializable {


     private int usuarioId;
     private String usuarioLogin;
     private String usuarioNome;
     private String usuarioSenha;
     private String usuarioPermicao;

    public Usuario() {
    }

	
    public Usuario(int usuarioId) {
        this.usuarioId = usuarioId;
    }
    public Usuario(int usuarioId, String usuarioLogin, String usuarioNome, String usuarioSenha, String usuarioPermicao) {
       this.usuarioId = usuarioId;
       this.usuarioLogin = usuarioLogin;
       this.usuarioNome = usuarioNome;
       this.usuarioSenha = usuarioSenha;
       this.usuarioPermicao = usuarioPermicao;
    }
   
     @Id 

    
    @Column(name="usuario_id", unique=true, nullable=false)
    public int getUsuarioId() {
        return this.usuarioId;
    }
    
    public void setUsuarioId(int usuarioId) {
        this.usuarioId = usuarioId;
    }

    
    @Column(name="usuario_login", length=80)
    public String getUsuarioLogin() {
        return this.usuarioLogin;
    }
    
    public void setUsuarioLogin(String usuarioLogin) {
        this.usuarioLogin = usuarioLogin;
    }

    
    @Column(name="usuario_nome", length=30)
    public String getUsuarioNome() {
        return this.usuarioNome;
    }
    
    public void setUsuarioNome(String usuarioNome) {
        this.usuarioNome = usuarioNome;
    }

    
    @Column(name="usuario_senha", length=100)
    public String getUsuarioSenha() {
        return this.usuarioSenha;
    }
    
    public void setUsuarioSenha(String usuarioSenha) {
        this.usuarioSenha = usuarioSenha;
    }

    
    @Column(name="usuario_permicao", length=80)
    public String getUsuarioPermicao() {
        return this.usuarioPermicao;
    }
    
    public void setUsuarioPermicao(String usuarioPermicao) {
        this.usuarioPermicao = usuarioPermicao;
    }




}


